### ISSUE TITLE
Running Jupyter on AWS

### ISSUE THREAD

**Issue by kjgarza** [datacite/datacite#427]
Certain analysis we need to perform cosume significant time and machine resources. Having a jupyter instance running in the cloud would make this easier and can be working 24/7. 

The proposal is to run a docker container running Jupyter, in the same way we run other services. 

- The image already exists and I have been using it to run anayses.
- its basically a docker compose cofnigured to use jupyter/datascience-notebook image and a file structure for scripts.

ToDo

- We are missing the deployment to ECS. Create a github repo to keeps the scripts and the docker-compose files. 
- Storage for datafiles. We might need to store files in a separated device to the container, such as S3. I need to figure out how to do this.

A disadvantage of this is where to keep the Input files and output files.

**Comment by kjgarza** [comment]
the docker compose file is very simple:


```yaml


version: '2'

services:
  dashboard:
    image: jupyter/datascience-notebook
    # image: visualisation_dashboard:nopass
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - NB_UID=1000

```
